const src = require("debug");

let productos = [
    {
        id: 1,
        foto : '/images/products/air-force.jpg ' ,
        nombre: "Zapatillas Nike Air Force 1" ,
        marca: "Marca: Nike",
        color : "Color: Blanco" ,
        talle : "Talle: 42" ,
        comentario:" Comentarios : 12" ,
    },
    {
        id: 2,
        foto : "/images/products/air-force-1-botas-wWrQ12.jpg" ,
        nombre: "Zapatillas Nike Air Force 1 Boots" ,
        marca: "Marca: Nike",
        color : "Color: Blanco" ,
        talle : "Talle: 39 ",
        comentario:" Comentarios : 120" ,
    },
    {
        id: 3,
        foto : "/images/products/air-max-270.jpg",
        nombre: "Zapatillas Nike Air Max 270" ,
        marca : "Marca: Nike",
        color : "Color: Rosa" ,
        talle : "Talle: 38" ,
        comentario:" Comentarios : 520" ,
    },
    {
        id: 4,
        foto : "/images/products/converse-PRINT.jpg",
        nombre: "Zapatillas Converse Plataforma " ,
        marca: "Marca: Converse",
        color : "Color: Animal Print" ,
        talle : "Talle: 40" ,
        comentario:" Comentarios : 115" ,
    },
    {
        id: 5,
        foto : "/images/products/forum-bold.jpg",
        nombre: "Zapatillas Adidas Forum Bold" ,
        marca : "Marca: Adidas",
        color : "Color: Blanco y azul" ,
        talle : "41" ,
        comentario:" Comentarios : 13" ,
    },
    {
        id: 6,
        foto : "/images/products/jordan-air-1.jpg",
        nombre: "Zapatillas Nike Air Jordan 1" ,
        marca: "Marca: Nike",
        color : "Color: Negro" ,
        talle : "Talle: 42" ,
        comentario:" Comentarios : 48" ,
    },
    {
        id: 7,
        foto : "/images/products/jordan-11.jpg",
        nombre: "Zapatillas Nike Air Jordan 11" ,
        marca: "Marca: Nike",
        color : "Color: Negro y rojo" ,
        talle : "Talle: 44" ,
        comentario:" Comentarios : 132" ,
    },
    {
        id: 8,
        foto : "/images/products/puma-rs.jpg",
        nombre: "Zapatillas Puma RS- Fast" ,
        marca: "Marca: Puma",
        color : "Color: Blanco y rojo" ,
        talle : "Talle: 41" ,
        comentario:" Comentarios : 1212" ,
    },
    {
        id: 9,
        foto : "/images/products/superstar.jpg",
        nombre: "Zapatillas Adidas Superstar" ,
        marca: "Marca: Adidas",
        color : "Color: Blanco y lila" ,
        talle : "Talle: 35" ,
        comentario:" Comentarios : 112" ,
    },
    {
        id: 10,
        foto :  "/images/products/vans.jpg",
        nombre: "Zapatillas Vans Old Skool" ,
        marca: "Marca: Vans",
        color : "Color: Negro" ,
        talle : "Talle: 42" ,
        comentario:" Comentarios : 512" ,
    },
    {
        id: 11,
        foto :  "/images/products/taylor-all-move.jpg",
        nombre: "Zapatillas Chuck Taylor All Star Move" ,
        marca : "Marca: Converse",
        color : "Color: Blanco" ,
        talle : "Talle: 39" ,
        comentario:" Comentarios : 712" ,
    },
    {
        id: 12,
        foto : "/images/products/forum-mid.jpg",
        nombre: "Zapatillas Adidas Forum Mid" ,
        marca : "Marca: Adidas",
        color : "Color: Blanco" ,
        talle : "41" ,
        comentario:" Comentarios : 130" ,
    },
]

module.exports = productos;